name: Show UT Coverage

description: |
  This action creates a check on GitHub that displays the coverage results.

runs:
  using: "node16"
  main: "index.js"

inputs:
  github-token:
    description: "The GitHub token used to authenticate API requests."
    required: true

outputs:
  check-id:
    description: "The ID of the created check on GitHub."

branding:
  icon: "check-square"
  color: "green"
